sudo: required
services:
 - docker

before_install:
 - docker build -t aye20dockerhub/docker-react -f dockerfile.dev .
 
script:
 - docker run -e CI=true aye20dockerhub/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react-4"
 env: "docker-react-4-env"
 bucket_name: "elasticbeanstalk-us-east-1-013273932492"
 bucket_path: "docker-react-4"
 on:
  branch: master
 access_key_id: 
  secure: $AWS_ACCESS_KEY
 secret_access_key: "$AWS_SECRET_KEY"
